### ISSUE TITLE
Trying to set a document with a different schema

### ISSUE THREAD

**Issue by ZombiEquinox** [tgecho/react-prosemirror#11]
I am trying to get the output to go to a Mongo Database, when setting up the getInitialState I keep getting the error "Trying to set a document with a different schema" when inspecting it says that it's react-prosemirror that is giving the error. how do you have your schema set up, I am using this as an article writer, so I have more fields than just the ProseMirror. Does this not play well with other fields?

**Comment by tgecho** [comment]
The only schema that react-prosemirror sets is the one you pass in the options prop. It sounds like you have some sort of mismatch, but I can't say for certain without a bit of example code.

**Comment by jefffriesen** [comment]
I hit the same error with the minimal example in the Readme:

```
import React from 'react'
import ProseMirror from 'react-prosemirror'

const TextArea = React.createClass({
  getInitialState() {
    return {value: 'Hello World!'}
  },
  render() {
    return <ProseMirror value={this.state.value} onChange={this.onChange} />
  },
  onChange(value) {
    this.setState({value})
  }
})
```

<img width="540" alt="screen shot 2016-02-06 at 11 50 21 am" src="https://cloud.githubusercontent.com/assets/445733/12868644/d76f3418-ccc7-11e5-883f-a8695cbc078e.png">

I'm completely new to this, but it looks like docFormat is a required option. Doing this let's me get past the error and get it rendering:

```
<ProseMirror value={this.state.value} onChange={this.onChange} options={{docFormat: 'html'}} />
```

Maybe the readme could be updated and the options.docFormat propTypes required?  I could do a PR but there may be more to this still.

**Comment by tgecho** [comment]
Ah, so this is a case of bad documentation on my part. The [ProseMirror doesn't require `docFormat`](http://prosemirror.net/ref.html#docFormat) and defaults to a raw `Node` object. I'm hesitant to override this default or add an extra requirement, even though most people likely want to use one of the string based formats such as markdown or html.

I'll at least update the example so it's not broken by default (see https://github.com/tgecho/react-prosemirror/commit/8ac966f90e709849143b42bde5d938a51bf19ced). Thanks!

Does this make sense @ZombiEquinox?

**Comment by jefffriesen** [comment]
It makes sense not to require the option if it's not required by ProseMirror. Is it possible to fix it so that so that it will work without passing in options?

**Comment by jefffriesen** [comment]
Continuing along the lines of getting copy/paste instant gratification when setting up react-prosemirror, it may be nice to export the ProseMirror plugins from `react-prosemirror` so users don't have to dive down into the ProseMirror repo. It would pave over npm inconsistencies that people run into and make a nicer API. For example, I had to do this:

```
import 'react-prosemirror/node_modules/prosemirror/dist/menu/tooltipmenu'
import 'react-prosemirror/node_modules/prosemirror/dist/markdown'
```

instead of 

```
import 'prosemirror/dist/menu/tooltipmenu'
import 'prosemirror/dist/markdown'
```

If you exported them from the repo like this:

```
export {markdown} from './node_modules/prosemirror/dist/markdown'   // not sure if it's exactly like this
```

Then we could import them more easily and consistently like:

```
import 'react-prosemirror/markdown
```

I haven't looked closely enough at the code to see if the above would work, but it would be along these lines. Thanks for putting this together. Prosemirror so far looks like a really impressive library.

**Comment by tgecho** [comment]
Well, the trick is that docFormat _isn't_ actually required. Per ProseMirror's docs, if you don't specify one PM will default to accepting one of its internal Node objects. Unfortunately most people will probably want to use one of the string based formats.

The import paths are a bummer, but I also don't think this is the right place to solve it. There are a bunch of things that you might want to import from PM, and I don't want to get in the business of reexporting most of PM. What I currently do is alias "prosemirror" to "prosemirror/dist" in my webpack config.

**Comment by jefffriesen** [comment]
Makes sense about the plugin paths. I can see that. thanks.

**Comment by ZombiEquinox** [comment]
So I eventually got Mongo to read the output of the component. I am still getting the same error though when trying to edit an it now. 
So on one page we are using an edit button to link to same page as the create but with the id attached. 

```
    let url ='#/NewArticle/' + this.props.rowData._id;
        return (
            <ul style={ {listStyleType:"none"} }>
                <li style={ {display: "inline"} }><a href={url}><FontAwesome name="pencil" /> Edit </a></li>
                <li style={ {display: "inline"} }><a onClick={this.remove}><FontAwesome name="trash" /> Delete </a></li>
            </ul>
)
```

we are using <a href="http://griddlegriddle.github.io/Griddle/">React Griddle</a> to display the data on this page. 

on the create/update page we are pulling in the data,

```
componentWillMount(){
    if(this.props.params.id){
      superagent.get("http://localhost:3030/api/v1.0/article/id/" + this.props.params.id).end((err, res) => {
        if(err){
          console.log(err);
        } else {
          this.setState({content: res.body.content});
        }
      });
    }
  },
```

the Schema for ProseMirror is

```
getInitialState() {
    return {
      options: {
        menuBar: true,
        tooltipMenu: true,
        autoInput: true,
        docFormat: 'html'
      },
      content: ""
    }
  },
```

and the schema for my articles are 

```
    var articleSchema = mongoose.Schema({
        title:String,
        author:String,
        type: String,
        images: {type: [String], default: 'http://lorempixel.com/640/480/people/'},
        datePublished: { type: Date, default: Date.now },
        content: String,
        options: {
            menuBar: {type: Boolean, default: true},
            tooltipMenu: {type: Boolean, default: true},
            autoInput: {type: Boolean, default: true},
            docFormat: {type: String, default: 'html'}
        }
    })
    var Article = mongoose.model("article", articleSchema, "articles");
```

i've tried taking out almost everything i could think of, and making the getInitialState match the schema from the API, but every time I link to the page with ProseMirror via the edit button, I get the Schema error. 

I have yet to get the page to even load via the edit button, I can link to a blank page just fine, but as soon as I attach the ID, it get Uncaught Error: Trying to set a document with a different schema.

**Comment by tgecho** [comment]
@ZombiEquinox thanks for the code snippets. I'm still not sure how to figure out what's wrong with what you've written here. Can you also include a snippet of where you actually render the `<ProseMirror />` component?

**Comment by ZombiEquinox** [comment]
@tgecho 

```
    <Col md={12}>
      <form ref="articleForm" onSubmit={this.createArticle}>
        <Row>
          <Input type="select" ref="type" label="Type of Article" placeholder="select" >
            <option value="">Select</option>
            <option value="Member Perks">Member Perks</option>
            <option value="Specialized Training">Specialized Training</option>
            <option value="Events & Announcements">Events & Annoucements</option>
          </Input>
        </Row>
        <Row>
          <Input type="file" ref="image" label="Featured Image" help="Lorem Ipsum Help Text"/>
        </Row>
        <Row>
          <Input type="text" ref="author" label="Author" placeholder="Author of Article"/>
        </Row>
        <Row>
          <Input type="text" ref="title" label="Title" placeholder="Enter Title" />
        </Row>
        <Row>
          <ProseMirror value={content} onChange={this.updateContent} options={options} ref="pm"/>
        </Row>
        <Row>
          <br/>
          <ButtonInput type="submit" value="Submit"/>
        </Row>
      </form>
    </Col>
```

this is the form layout of how we are using your prosemirror. I really am hoping we can get this working correctly, because this is exactly what we need for our project. I am betting its something small I am overlooking. thanks for your help.

**Comment by tgecho** [comment]
Can you put this code right above the `<ProseMirror ....`:
`{console.log(content, options)}`
...and tell me what gets output to the console?

Also, a snippet of your `this.updateContent` function could be helpful.

Basically the key is to make sure the right data is actually being fed into the props of the component.

**Comment by ZombiEquinox** [comment]
so the console.log returns 

<code>
Object {menuBar: true, tooltipMenu: true, autoInput: true, docFormat: "html"}
</code>

the content part returns nothing since I have it default to blank. I took out the updateContent function, as I am now just getting the HTML content on submit.

<pre><code>
  createArticle(event) {
    event.preventDefault();
    var article = {
      type: this.refs.type.getValue(),
      author: this.refs.author.getValue(),
      title: this.refs.title.getValue(),
      images: this.refs.images.getValue(),
      content: this.refs.pm.getContent('html')
    }
    superagent.post("http://localhost:3030/api/v1.0/article").send(article).end((err, res) => {
      err ? console.log(err) : console.log(res);
    });
    this.replaceState(this.getInitialState())
    this.refs.articleForm.reset();
  },
</code></pre>

I can only get this information when creating a new item, when going to edit an item, so going to 
<code>
#/NewArticle/ + this.props.rowData._id
</code>
which is pulling in the _id from Mongo, I get the Uncaught Error, and the page doesn't even load. 

What I had before for my updateContent was what you have in your demo

<pre><code>
  updateContent(content) {
    const {docFormat} = this.state.options
    this.setState({
      content,
      html: docFormat === 'html'
        ? content
        : this.refs.pm.getContent('html')
    })
  },
</code></pre>

hopefully this helps I will provide any other info you need, thanks.

**Comment by tgecho** [comment]
I really don't know what to make of this from what I can see here. This error should really only happen if you don't include a docFormat or somehow pass in an invalid content value. From what I can see that doesn't seem likely. The only two steps I can think of next are to **get a full stack trace from the error** (I should have asked for this at the start).

For troubleshooting purposes, I'd try hardcoding the docFormat and `console.log` the content.

```
{console.log(content)}
<ProseMirror value={content} onChange={this.updateContent} options={{docFormat: 'html'}} ref="pm"/>
```

This ensures that the docFormat can never vary, and we can monitor the content. If it ever logs as anything other than a string (undefined and null should be fine as well), you will probably get a schema error.

**Comment by ZombiEquinox** [comment]
ok, so i figured out my problem. basically, I am an idiot. I forgot I had a different component that was also using prosemirror, that I wasn't using. so every time it was compilling it was freaking out becuase it was trying to read two different renders of prosemirror. so thats why it was trying to read two different schemas.  So once i deleted the other component and re-compiled everything it was working just fine. My apologies and thank you for your help, it is still very informative. You can probably close this issue now.

**Comment by tgecho** [comment]
Glad you got it figured out!
