### ISSUE TITLE
Changing the input value does not update _lastValue

### ISSUE THREAD

**Issue by kbrownlees** [tgecho/react-prosemirror#13]
It seems that the .change handler for pm is only called for user initiated changes (setContent doesn't cause it be triggered). This means that the wrapper never sets a _lastValue if a new value is passed into it (until the user changes something).

Flow which causes this:

Start with value1
Modify to value2 (via keyboard)
Set value={value1}
Set value={value2}

value2 never gets repopulated because _lastValue is still set to value2, so setContent is never called.

I 'fixed it' locally by adding the follow after setContent:
`this._lastValue = this.pm.getContent(this.props.options.docFormat);`

**Comment by tgecho** [comment]
Thanks!

**Comment by will-hart** [comment]
:+1:  Thanks - this was giving me a headache earlier today :)
