### ISSUE TITLE
'prosemirror' cannot be found

### ISSUE THREAD

**Issue by ZombiEquinox** [tgecho/react-prosemirror#16]
I just updated to 0.2.0, when I run my compiler it throws out an error saying that 'prosemirror' cannot be found in /node_modules/react-prosemirror/dist looking at the index.js and taking out _prosemirror = require('prosemirror') it runs just fine, but then it can't find _prosemirror when you call it on line 57 for 
`this.pm = new _prosemirror.ProseMirror(options)`

also after updating it couldn't find markdown, or any of the other options that were in the dist folder, it appears they have all been deleted, even after uninstalling it and reinstalling it. this is a great rich text editor, and I hope we can figure out whats going on, especially since the page I am currently doing some work on is the page that has this component.

**Comment by tgecho** [comment]
The primary change in 0.2.0 was that I moved ProseMirror to peerDependancies. This means that newer versions of NPM will no longer automatically install it, but I'd thought that it would remain installed for you if you simply upgraded.

Can you try running `npm install --save prosemirror` and see if that fixes it?

**Comment by ZombiEquinox** [comment]
I rolled back to v0.1.4, which installed fine and ran fine. I took your suggestion and installed prosemirror, then updated to v0.2.0, recompiled the app, and it works fine now. so you may want to re-add prosemirror, becuase installing a fresh copy of react-prosemirror 0.2.0 doesn't seem to work without it.

**Comment by tgecho** [comment]
Glad that worked!

The readme was updated to add prosemirror to the install instructions with `npm install --save react-prosemirror prosemirror`

I think the peerDependancies is the right place (this was discussed in #12 and #14). I'm not sure why the upgrade seemed to break, but npm should bug you about installing missing peerDependencies.

Thanks for pinging!
