### ISSUE TITLE
How to limit max height?

### ISSUE THREAD

**Issue by zhaoyao91** [tgecho/react-prosemirror#17]

**Comment by tgecho** [comment]
This question is more about ProseMirror itself than this project (which is just a React wrapper), however...

You might try experimenting with setting some css such as 

```
.ProseMirror-content {
  max-height: 200px;
  overflow: auto;
}
```

This seems to work at first glance, but you'll want to test it to make sure there aren't any unwanted side effects.

**Comment by tgecho** [comment]
Closing this to tidy things up. Please feel free to reopen if you feel it is warranted.
