### ISSUE TITLE
<embed> tag is cleared...

### ISSUE THREAD

**Issue by zhaoyao91** [tgecho/react-prosemirror#18]
In html model, although the passed-in value has some tags like <embed> that this editor can not render, it should not clear them away when I call `getContent`.

How to support video?

**Comment by tgecho** [comment]
I'm afraid stripping unrecognized markup is a key part of how ProseMirror works. It's also out of scope for this project, which is focused on offering a simple React component for PM. I'd take a look at the official docs for info about extending the PM document models: https://prosemirror.net

Good luck!
