### ISSUE TITLE
react-prosemirror requires "babbel-loader?optional=runtime"

### ISSUE THREAD

**Issue by FPurchess** [tgecho/react-prosemirror#4]
Since react-prosemirror relies on `Object.assign` it needs to be compiled with babel-runtime. Hence it would be great to update to update the README for other developers.

```
{
  test: /\.js?$/,
  include: [/prosemirror/, /react-prosemirror/],
  loaders: ["babel-loader?optional=runtime"]
},
```

**Comment by tgecho** [comment]
If I'm not mistaken, something like [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) is actually what is needed here. I've added a note about that to the readme, along with the basic required options to use Babel 6. Please let me know if I missed something. Thanks!
