### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by AlbanMinassian** [tgecho/react-prosemirror#7]
Hello, npm package seem wrong. 

```
npm install react-prosemirror
ls /node_modules/react-prosemirror
```

return

```
..                    
LICENSE               
package.json          
README.md             
```

No js file !
Ami44

**Comment by zmsp** [comment]
I have the same problem. `npm install git+git@github.com:tgecho/react-prosemirror.git` seems to be failing.

**Comment by will-hart** [comment]
I think this is answered in the installation section https://github.com/tgecho/react-prosemirror#installation.

Not sure why it isn't on `npm` though.

**Comment by tgecho** [comment]
Prosemirror is now fully npm installable (https://discuss.prosemirror.net/t/release-0-1-1/126), so I'll be getting this library up as well once I do a quick compatibility check.

**Comment by will-hart** [comment]
:+1:  I've been running it `npm install`ed from github with no problems...

**Comment by tgecho** [comment]
This should be all set: https://www.npmjs.com/package/react-prosemirror
