### ISSUE TITLE
Fails for empty text

### ISSUE THREAD

**Issue by laszbalo** [tgecho/react-prosemirror#8]
When I delete all the text inside the editor, then the editor stops updating itself.
The root cause of this problem is that during the initiation of [this._lastValue](https://github.com/tgecho/react-prosemirror/blob/master/index.js#L29), this.props.value becomes falsy. I think it could be easily fixed by checking whether this.props.value is undefined instead.

**Comment by tgecho** [comment]
Thanks @laszbalo!

**Comment by laszbalo** [comment]
Hi, I think this issue is still persist. Inside the componentWillUpdate method, when the this._lastValue variable gets its initial value, either with value or valueLink.value props, if either of those are falsy, then the assignment falls back to the defaultValue prop(which is undefined in my case).

It could be solved, by adding the empty string as the default clause

``` javascript
componentWillMount() {
  this._lastValue = this.props.value ||
    ('valueLink' in this.props && this.props.valueLink.value) ||
    this.props.defaultValue ||
    '';
  ...
```

however, it will fail again, if the value of the value props or valueLink.value is 0 (gets converted to '').
I think, it would be better to check whether value or valueLink are defined instead. 
What do you think?

**Comment by tgecho** [comment]
You are absolutely right. My particular use of this initializes the value from outside, so I was just missing this (not very) edge case. I'm afraid it wasn't quite as simple as ending with an empty string, as that would break the json docFormat. I think I figured out a reasonably satisfactory solution. Thank you so much for pointing this out, and please let me know if it does/doesn't work for you!

https://github.com/tgecho/react-prosemirror/commit/80ea0ba79f9412aa0016547e21857d5bfdfd22ba

**Comment by laszbalo** [comment]
Sorry, what I meant in my previous comment was that having the empty string as the last expression would not solve the core issue and would introduce a new one. (converting 0 to the empty string)

I just tested the latest version. It solves the problem of value is the empty string, however it introduces new ones:
1. if defaultValue was set, it throws an error
2. ~~if I have the document object `const doc = { value: 0 }`, and I call `<ProseMirror value={doc.value} />`, then would expect to see one 0 character, instead of the empty string (this is the very same [edge] case I was trying to highlight in my previous comment)~~ After some thinking, I am not sure about this. The original ProseMirror expect a string, should react-prosemirror convert any value (numbers, objects, null) to string before passing it to ProseMirror? Probably not.
3. and lastly my biggest problem: I want to define my own schema, because I want to prevent the users to paste in arbitrary html, for that I can't have [docFormat](https://github.com/ProseMirror/prosemirror/blob/f3ea479481d987ca7145424c6356b25fe578d0f3/src/edit/main.js#L57) set to null(or anything falsy). I want it to be 'text', but the current implementation overrides it.

I have changed react-prosemirror like this, it fixes 1. and 3.

``` javascript
  const {value, valueLink, defaultValue} = this.props;
  this._lastValue = typeof value !== 'undefined' ? value : 
    valueLink && typeof valueLink.value !== 'undefined' ? valueLink.value : 
    typeof defaultValue !== 'undefined' ? defaultValue : 
    ''

   var options = Object.assign({ doc: this._lastValue }, this.props.options);
   this.pm = new _edit.ProseMirror(options); 
```

[Here are some tests as well](http://jsbin.com/gutuli/edit?js,console)

It works great for me, but not sure about the json docformat.

**Comment by laszbalo** [comment]
Now I see what you meant by the json document fromat error when the empty string is the last expression. How about this? If react-prosemirror component is created without either value, valueLink or defaultValue, then Prosemirror would be initiated without the doc property. In this case ProseMirror could still respect the docFormat  that was passed to it initially.

```javascript
  const {value, valueLink, defaultValue} = this.props;
  this._lastValue = typeof value !== 'undefined' ? value : 
    valueLink && typeof valueLink.value !== 'undefined' ? valueLink.value : 
    typeof defaultValue !== 'undefined' ? defaultValue;

    let options;
    if(typeof this._lastValue !== 'undefined') options.doc = this._lastValue;
    Object.assign(options, this.props.options);
   
   this.pm = new _edit.ProseMirror(options); 
```

**Comment by tgecho** [comment]
Hrm. Clearly what was supposed to be a trivial wrapper library will in fact require a proper test suite. :)
1. Ah, but only if the defaultValue is set to an empty string. Grh.
2. I tend to agree. I'm trying to avoid being too clever. However, if checking more carefully for `undefined` leads to the number zero being passed into PM (and getting stringified), I'm not opposed.
3. I don't think that will be a problem. As I understand it, the docFormat passed into the ProseMirror constructor is only used to interpret the initial doc variable. As far as I can tell it's never used again. The other place that react-prosemirror uses it is when calling `getContent`. In other words, unless I'm mistaken, setting it to null shouldn't affect your ability to use a custom schema (a separate option).

I just pushed up https://github.com/tgecho/react-prosemirror/commit/b0fe85a1d4c7bdf5a769b760136c29aec6acff23, which seems to be a bit more reliable. I'll actually work up a tiny but proper test suite, using your tests as a starting point. Thanks!

**Comment by laszbalo** [comment]
I am glad I could help :smile:
1. Just a quick question: Is defaultValue really needed?
2. I thought the same thing first, but now I tend to gravitate towards passing everything to ProseMirror as it was provided by a developer, and in the case of an exception, just let ProseMirror fail as it would do without react-prosemirror being  a proxy layer.
3. Ignore this please, that is my mistake. Because of #10 , I commented out my custom schema, and forget to uncomment it when I was testing.

**Comment by tgecho** [comment]
1. I think so. I have a few cases where I don't want to fully control the value but I want to set the initial value. This also follows the pattern used by standard React form components.
2. In the case of the number `0`, this is what we're doing. Sometimes ProseMirror will actually coerce it to a string. I think we're on the same page: just pass the stuff to PM and let it do its thing.

Here's a first batch of initial value tests: https://github.com/tgecho/react-prosemirror/commit/96fb25290fc1436330e57ac97e643c37618454f0. They're a bit brute force, but hopefully cover all of the bases we discussed. Please feel free to add more!

**Comment by tgecho** [comment]
I believe this is sorted out now. Please feel free to chime in if that's not the case. Thanks!

**Comment by laszbalo** [comment]
Hi, sorry for the late reply. Yeah, that is sorted out by now. Thanks for your help.
