### ISSUE TITLE
Display Name is '.'

### ISSUE THREAD

**Issue by laszbalo** [tgecho/react-prosemirror#9]
Hi @tgecho,

When I browse the rendered tree in React Dev Tools, the react-prosemirror component has a name '.'
I am using the ES2015 way for creating components, but I belive you could either add displayName property when calling createClass **or** let React to automatically figure it out for you, by exporting ProseMirror the following way:

``` javascript
const ProseMirror = React.createClass({...});
export default ProseMirror;
```

With thanks,
Laszlo

**Comment by tgecho** [comment]
Thanks! Usually my components are single files named after the component, so I got used to babel's auto naming.

**Comment by laszbalo** [comment]
Great! Thanks a lot!
